/**
 * @fileoverview gRPC-Web generated client stub for net.devh.boot.grpc.example
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: product.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.net = {};
proto.net.devh = {};
proto.net.devh.boot = {};
proto.net.devh.boot.grpc = {};
proto.net.devh.boot.grpc.example = require('./product_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.net.devh.boot.grpc.example.ProductServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.net.devh.boot.grpc.example.ProductServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.net.devh.boot.grpc.example.GetProductRequest,
 *   !proto.net.devh.boot.grpc.example.ProductResponse>}
 */
const methodDescriptor_ProductService_GetProduct = new grpc.web.MethodDescriptor(
  '/net.devh.boot.grpc.example.ProductService/GetProduct',
  grpc.web.MethodType.UNARY,
  proto.net.devh.boot.grpc.example.GetProductRequest,
  proto.net.devh.boot.grpc.example.ProductResponse,
  /**
   * @param {!proto.net.devh.boot.grpc.example.GetProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.net.devh.boot.grpc.example.ProductResponse.deserializeBinary
);


/**
 * @param {!proto.net.devh.boot.grpc.example.GetProductRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.net.devh.boot.grpc.example.ProductResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.net.devh.boot.grpc.example.ProductResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.net.devh.boot.grpc.example.ProductServiceClient.prototype.getProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/GetProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProduct,
      callback);
};


/**
 * @param {!proto.net.devh.boot.grpc.example.GetProductRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.net.devh.boot.grpc.example.ProductResponse>}
 *     Promise that resolves to the response
 */
proto.net.devh.boot.grpc.example.ProductServicePromiseClient.prototype.getProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/GetProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProduct);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.net.devh.boot.grpc.example.AddProductRequest,
 *   !proto.net.devh.boot.grpc.example.ProductResponse>}
 */
const methodDescriptor_ProductService_AddProduct = new grpc.web.MethodDescriptor(
  '/net.devh.boot.grpc.example.ProductService/AddProduct',
  grpc.web.MethodType.UNARY,
  proto.net.devh.boot.grpc.example.AddProductRequest,
  proto.net.devh.boot.grpc.example.ProductResponse,
  /**
   * @param {!proto.net.devh.boot.grpc.example.AddProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.net.devh.boot.grpc.example.ProductResponse.deserializeBinary
);


/**
 * @param {!proto.net.devh.boot.grpc.example.AddProductRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.net.devh.boot.grpc.example.ProductResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.net.devh.boot.grpc.example.ProductResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.net.devh.boot.grpc.example.ProductServiceClient.prototype.addProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/AddProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_AddProduct,
      callback);
};


/**
 * @param {!proto.net.devh.boot.grpc.example.AddProductRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.net.devh.boot.grpc.example.ProductResponse>}
 *     Promise that resolves to the response
 */
proto.net.devh.boot.grpc.example.ProductServicePromiseClient.prototype.addProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/AddProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_AddProduct);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.net.devh.boot.grpc.example.UpdateProductRequest,
 *   !proto.net.devh.boot.grpc.example.ProductResponse>}
 */
const methodDescriptor_ProductService_UpdateProduct = new grpc.web.MethodDescriptor(
  '/net.devh.boot.grpc.example.ProductService/UpdateProduct',
  grpc.web.MethodType.UNARY,
  proto.net.devh.boot.grpc.example.UpdateProductRequest,
  proto.net.devh.boot.grpc.example.ProductResponse,
  /**
   * @param {!proto.net.devh.boot.grpc.example.UpdateProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.net.devh.boot.grpc.example.ProductResponse.deserializeBinary
);


/**
 * @param {!proto.net.devh.boot.grpc.example.UpdateProductRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.net.devh.boot.grpc.example.ProductResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.net.devh.boot.grpc.example.ProductResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.net.devh.boot.grpc.example.ProductServiceClient.prototype.updateProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/UpdateProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_UpdateProduct,
      callback);
};


/**
 * @param {!proto.net.devh.boot.grpc.example.UpdateProductRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.net.devh.boot.grpc.example.ProductResponse>}
 *     Promise that resolves to the response
 */
proto.net.devh.boot.grpc.example.ProductServicePromiseClient.prototype.updateProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/UpdateProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_UpdateProduct);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.net.devh.boot.grpc.example.DeleteProductRequest,
 *   !proto.net.devh.boot.grpc.example.BooleanResponse>}
 */
const methodDescriptor_ProductService_DeleteProduct = new grpc.web.MethodDescriptor(
  '/net.devh.boot.grpc.example.ProductService/DeleteProduct',
  grpc.web.MethodType.UNARY,
  proto.net.devh.boot.grpc.example.DeleteProductRequest,
  proto.net.devh.boot.grpc.example.BooleanResponse,
  /**
   * @param {!proto.net.devh.boot.grpc.example.DeleteProductRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.net.devh.boot.grpc.example.BooleanResponse.deserializeBinary
);


/**
 * @param {!proto.net.devh.boot.grpc.example.DeleteProductRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.net.devh.boot.grpc.example.BooleanResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.net.devh.boot.grpc.example.BooleanResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.net.devh.boot.grpc.example.ProductServiceClient.prototype.deleteProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/DeleteProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_DeleteProduct,
      callback);
};


/**
 * @param {!proto.net.devh.boot.grpc.example.DeleteProductRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.net.devh.boot.grpc.example.BooleanResponse>}
 *     Promise that resolves to the response
 */
proto.net.devh.boot.grpc.example.ProductServicePromiseClient.prototype.deleteProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/net.devh.boot.grpc.example.ProductService/DeleteProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_DeleteProduct);
};


module.exports = proto.net.devh.boot.grpc.example;

