/**
 * @fileoverview gRPC-Web generated client stub for frontend
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: product.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.frontend = require('./product_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.frontend.ProductServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.frontend.ProductServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.frontend.ProductList>}
 */
const methodDescriptor_ProductService_GetProducts = new grpc.web.MethodDescriptor(
  '/frontend.ProductService/GetProducts',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.frontend.ProductList,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.frontend.ProductList.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.frontend.ProductList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.frontend.ProductList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.frontend.ProductServiceClient.prototype.getProducts =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/frontend.ProductService/GetProducts',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProducts,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.frontend.ProductList>}
 *     Promise that resolves to the response
 */
proto.frontend.ProductServicePromiseClient.prototype.getProducts =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/frontend.ProductService/GetProducts',
      request,
      metadata || {},
      methodDescriptor_ProductService_GetProducts);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.frontend.ProductId,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ProductService_DeleteProduct = new grpc.web.MethodDescriptor(
  '/frontend.ProductService/DeleteProduct',
  grpc.web.MethodType.UNARY,
  proto.frontend.ProductId,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.frontend.ProductId} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.frontend.ProductId} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.frontend.ProductServiceClient.prototype.deleteProduct =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/frontend.ProductService/DeleteProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_DeleteProduct,
      callback);
};


/**
 * @param {!proto.frontend.ProductId} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.frontend.ProductServicePromiseClient.prototype.deleteProduct =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/frontend.ProductService/DeleteProduct',
      request,
      metadata || {},
      methodDescriptor_ProductService_DeleteProduct);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.frontend.ReviewUpdate,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ProductService_UpdateReview = new grpc.web.MethodDescriptor(
  '/frontend.ProductService/UpdateReview',
  grpc.web.MethodType.UNARY,
  proto.frontend.ReviewUpdate,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.frontend.ReviewUpdate} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.frontend.ReviewUpdate} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.frontend.ProductServiceClient.prototype.updateReview =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/frontend.ProductService/UpdateReview',
      request,
      metadata || {},
      methodDescriptor_ProductService_UpdateReview,
      callback);
};


/**
 * @param {!proto.frontend.ReviewUpdate} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.frontend.ProductServicePromiseClient.prototype.updateReview =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/frontend.ProductService/UpdateReview',
      request,
      metadata || {},
      methodDescriptor_ProductService_UpdateReview);
};


module.exports = proto.frontend;

